# Étape de construction
FROM node:latest AS build

# Définir le répertoire de travail pour l'étape de construction
WORKDIR /app

# Copier package*.json dans le répertoire de travail
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers dans le répertoire de travail
COPY . .

# Construire l'application Angular
RUN npm run build

# Étape de production avec Nginx
FROM nginx:alpine

# Copier les fichiers de build Angular vers le répertoire de Nginx
COPY --from=build /app/dist/front-end /usr/share/nginx/html

# Copier la configuration personnalisée de Nginx (si nécessaire)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exposer le port 8080
EXPOSE 8080

# Démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]
