FROM node:latest AS backend-build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN useradd -m myuser && chown -R myuser /app
USER myuser


EXPOSE 9428

CMD [ "npm", "run", "dev" ]
